import React from "react";
import "./Feature.css";

const FeatureContent = [
  {
    image: "assets/feature1.svg",
    description: "Simply add a keyword or a term related to your business in the slogan maker search box. Wait for the magic to happen.",
    title: "Search",
  },
  {
    image: "assets/feature2.svg",
    description: "Choose from thousands of options generated by the slogan maker that fit your needs.",
    title: "Select",
  },
  {
    image: "assets/feature3.svg",
    description: "Congrats on your new slogan. It's time to win the world!",
    title: "Stand out",
  },
];

const Feature = () => {
  return (
    <div className="cardContainer">
      <section className="cardItems">
        {FeatureContent.map((data, i) => (
          <div key={i} className="card-styles">
            <img src={data.image} alt={`${data.title}`} />
            <h5 className="cardTitle">{data.title}</h5>
            <p className="cardDescription">{data.description}</p>
          </div>
        ))}
      </section>
    </div>
  );
};

export { Feature };
